# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - release
  - devel

r_github_packages:
  - steverozen/hdpx
  - steverozen/SynSigGen
  - WuyangFF95/SynSigEval

before_install:
  - sudo apt-get update
